### ISSUE TITLE
Fixed: Not transmitting to mqtt

### ISSUE THREAD

**Issue by Dennis-NL** [cziter15/pelletmon#2]
Somehow i am not receiving anything over mqtt
It does send a /connect with the value "1" but nothing else

Sending commands does work

Any idea what i could have done wrong?

**Comment by cziter15** [comment]
First of all, make sure that CAN bus is properly connected. If everything is okay, then check VideNetRequestType. Sometimes command codee can be different and it probably depends on internal wiring/firmware version. I remember that someone had exactly same problem and he had to change ReadDone value.

**Comment by Dennis-NL** [comment]
With commands i mean controlling the kettle

Like sending a "0" to '/set/controller_enabled' disables the kettle and "1" enables it.
Controlling works, but i am not receiving anything

**Comment by cziter15** [comment]
Locate CAN response processing code in VideNetClient.

```
/* Process all incomming CAN frames. */
for (CAN_FRAME rx_frame; CAN0.read(rx_frame);)
{
	if (rx_frame.id == VIDE_NET_RESPONSE)
	{
		/* At the end of this scope, scoped sync will trigger synchronize queues on videNetRequests. */
		ksf::ksSafeListScopedSync scopedListSync(videNetRequests);

		/* Handle vide net packet. Handle plus remove handled requests. */
		for (auto& req : videNetRequests.getList())
		{
			if (req->onResponse(rx_frame))
				videNetRequests.queueRemove(req);
		}
	}
}
```

And modify it to print responses, you can use MQTT for this purpose:

```
/* Process all incomming CAN frames. */
for (CAN_FRAME rx_frame; CAN0.read(rx_frame);)
{
	if (rx_frame.id == VIDE_NET_RESPONSE)
	{
		/* Print response to MQTT log. */
		if (auto mqttConnSp = mqttConnWp.lock())
		{
			std::string debugMessage{"Recevied CAN frame: "};

			for (uint8_t i = 0; i < rx_frame.length; i++)
				debugMessage += ksf::to_string(rx_frame.data.byte[i]) + " ";

			mqttConnSp->publish("log", debugMessage);
		}
		
		/* At the end of this scope, scoped sync will trigger synchronize queues on videNetRequests. */
		ksf::ksSafeListScopedSync scopedListSync(videNetRequests);

		/* Handle vide net packet. Handle plus remove handled requests. */
		for (auto& req : videNetRequests.getList())
		{
			if (req->onResponse(rx_frame))
				videNetRequests.queueRemove(req);
		}
	}
}
```
It should dump responses into MQTT devicePrefix/log topic. First byte is request/response type. Please check and tell me about the results.

**Comment by Dennis-NL** [comment]
Changing ReadDone value to 0x43 worked for me

**Comment by cziter15** [comment]
Looks like I must address this somehow in the code ;)

**Comment by cziter15** [comment]
I've fixed issue on master branch. Please re-test using newest master version. (Please update dependencies of plafromio and project git code).
